### ISSUE TITLE
Duplicate records after using odata.nextLink

### ISSUE THREAD

**Issue by lf-novelt** [gpw13/xmart4#1]
Hello, 

Developer from xmart-api speaking.

Nice work implementing the `nextLink` support so quickly but it seems you're facing an issue with some missing records (tracked under https://github.com/novelt/xmart/issues/2745).
I think the issue is that the first query is not ordered the same way as the next ones, as the $skip parameter forces a sort on the Sys_ID column if the $orderBy is not provided, and if the $skip is not provided, the sort is just the default SQL storage sort.

_(an explicit sort is required for SQL proper pagination)_

Here are 2 possible solutions for you to try:
 1. also **provide the $skip parameter for the first query**, with value 0, like so https://portal-uat.who.int/xmart-api/odata/GPW13/RAW_INDICATOR?$skip=0
 2. or specify an explicit `$orderBy` https://portal-uat.who.int/xmart-api/odata/GPW13/RAW_INDICATOR?$orderBy=_RecordID

In the meanwhile, in xmart, we'll probably use the same default sorting whether the $skip parameter is provided or not.

Please tell me if you tried one or the other and if it helped.

**Comment by caldwellst** [comment]
@lf-novelt Thanks for the suggestions. Both solutions provided a working solution but I went with the `$skip=0` solution simply because it seemed more elegant to have a tiered set of queries starting with `$skip=0` to the final `$skip=k`.

**Comment by ChrisTantillo** [comment]
Nice work to both of you on this.  Thanks a lot Seth for helping us to test this "feature", it's really appreciated.

**Comment by lf-novelt** [comment]
Nice! Fyi, the sorting is now fixed on xmart side as well so $skip=0 and no $skip should yield the same results!
